name = "ShellFunctions"
uuid = "7ae72761-576b-497c-8476-fc363dd5d68d"
authors = ["Carl Morris <carl.morris.world@outlook.com>"]
version = "0.1.0"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
